/**
 * Distill a successful, replayable agent run into a reusable draft template.
 *
 * Called (best-effort, fire-and-forget) from reflectAndRemember's completion
 * path once the reflection pass judges a run "worth templating" — a
 * self-contained, repeatable job a reasonable operator would want to run
 * again with different inputs, as opposed to a one-off Q&A.
 *
 * Auto-generated templates are PRIVATE to the creating org: they land in the
 * same `AgentTemplate` table as community templates but are tagged
 * `configuration.autoGenerated = true` and must be excluded from the
 * cross-org community listing in GET /api/agent-templates (see that route).
 */
import { prisma } from '@/lib/prisma'
import { apiLogger } from '@/lib/logger'
import { embedTexts, embeddingsConfigured, cosineSimilarity } from '@/lib/rag/embeddings'
import { departmentsForTools } from '@/lib/templates/departments'

/** Cap on auto-generated templates retained per org; oldest evicted beyond this. */
export const MAX_AUTO_TEMPLATES_PER_ORG = 20

/** Cosine similarity at/above which a candidate is treated as a duplicate of an existing template. */
export const DUPLICATE_SIMILARITY_THRESHOLD = 0.86

export type ReplayableJudgment = {
  worthTemplating: boolean
  title?: string
  description?: string
  exampleInput?: string
}

/**
 * Pure: does this candidate embedding duplicate any existing auto-generated
 * template's embedding for this org? True as soon as any existing embedding
 * is at/above the threshold. Empty/mismatched vectors never match (cosineSimilarity
 * returns 0 for those), so a missing embedding (Voyage unconfigured) never
 * false-positives as a duplicate.
 */
export function isDuplicateTemplate(
  candidateEmbedding: number[],
  existingEmbeddings: number[][],
  threshold: number = DUPLICATE_SIMILARITY_THRESHOLD,
): boolean {
  if (candidateEmbedding.length === 0) return false
  return existingEmbeddings.some((existing) => cosineSimilarity(candidateEmbedding, existing) >= threshold)
}

/**
 * Pure: given existing auto-generated templates (oldest-first-safe — any
 * order, each with an id and createdAt) and a cap, return the ids to evict —
 * the oldest rows beyond the cap, so at most `cap - 1` remain before the new
 * row is inserted (leaving room for the one about to be created). Returns []
 * when already at or under the room needed.
 */
export function pickTemplatesToEvict(
  existing: Array<{ id: string; createdAt: Date | string | number }>,
  cap: number = MAX_AUTO_TEMPLATES_PER_ORG,
): string[] {
  if (existing.length < cap) return []
  const sorted = [...existing].sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime())
  // Room for one new row: keep at most (cap - 1) existing, evict the rest (oldest first).
  const keep = Math.max(cap - 1, 0)
  const evictCount = sorted.length - keep
  return evictCount > 0 ? sorted.slice(0, evictCount).map((t) => t.id) : []
}

export type AutoTemplateConfigInput = {
  objective: string
  integrations: string[]
  model: string
  executionId: string
  exampleInput?: string
  embedding?: number[]
}

/**
 * Pure: assemble the `configuration` JSON blob for an auto-generated
 * template. Tags every candidate with the shared tool→department taxonomy
 * (departmentsForTools) so BI-distilled "From your runs" templates
 * participate in the same department filter as the seed catalogue.
 */
export function buildAutoTemplateConfig(input: AutoTemplateConfigInput): Record<string, unknown> {
  const { objective, integrations, model, executionId, exampleInput, embedding } = input
  return {
    instructions: objective,
    integrations,
    model,
    autoGenerated: true,
    departments: departmentsForTools(integrations),
    sourceExecutionId: executionId,
    ...(exampleInput ? { exampleOutput: exampleInput } : {}),
    ...(embedding && embedding.length > 0 ? { embedding } : {}),
  }
}

export type MaybeCreateTemplateParams = {
  organizationId: string
  userId: string
  agentId: string
  executionId: string
  objective: string
  model: string
  integrations: string[]
  category?: string
  runSucceeded: boolean
  toolCallCount: number
  replayable: ReplayableJudgment
}

/**
 * Best-effort: distill a successful, replayable run into a draft
 * AgentTemplate. Never throws — any failure is logged and swallowed so it
 * can never break the run it's reflecting on.
 *
 * Skips unless: worthTemplating, the run succeeded, and at least one tool
 * was used (a pure Q&A run with zero tool calls isn't a reusable "job").
 * Deduplicates against this org's existing auto-generated templates by
 * embedding cosine similarity, and evicts the oldest auto-generated
 * templates once the per-org cap is exceeded.
 */
export async function maybeCreateTemplateFromRun(params: MaybeCreateTemplateParams): Promise<{ created: boolean; templateId?: string; reason?: string }> {
  const { organizationId, userId, agentId, executionId, objective, model, integrations, category, runSucceeded, toolCallCount, replayable } = params
  try {
    if (!replayable.worthTemplating) return { created: false, reason: 'not-worth-templating' }
    if (!runSucceeded) return { created: false, reason: 'run-not-successful' }
    if (toolCallCount < 1) return { created: false, reason: 'no-tools-used' }

    const title = (replayable.title || objective).slice(0, 200).trim() || 'Auto-generated template'
    const description = (replayable.description || '').slice(0, 2000)

    let candidateEmbedding: number[] = []
    let existingAutoTemplates: Array<{ id: string; createdAt: Date; configuration: unknown }> = []

    if (embeddingsConfigured()) {
      try {
        const [embedding] = await embedTexts([`${title}\n${description}`], { inputType: 'document' })
        candidateEmbedding = embedding ?? []
      } catch (error) {
        apiLogger.warn('maybeCreateTemplateFromRun: embedding failed, proceeding without dedupe', {
          organizationId, error: error instanceof Error ? error.message : String(error),
        })
      }
    }

    // All of this org's auto-generated templates (community/others' rows are
    // excluded by organizationId — auto-generated rows are per-org private).
    existingAutoTemplates = await prisma.agentTemplate.findMany({
      where: { organizationId, isActive: true },
      select: { id: true, createdAt: true, configuration: true },
      orderBy: { createdAt: 'asc' },
    }).then((rows) =>
      rows.filter((row) => {
        const config = row.configuration && typeof row.configuration === 'object' ? (row.configuration as Record<string, unknown>) : {}
        return config.autoGenerated === true
      }),
    )

    if (candidateEmbedding.length > 0) {
      const existingEmbeddings = existingAutoTemplates
        .map((row) => {
          const config = row.configuration && typeof row.configuration === 'object' ? (row.configuration as Record<string, unknown>) : {}
          return Array.isArray(config.embedding) ? (config.embedding as number[]) : []
        })
        .filter((vec) => vec.length > 0)
      if (isDuplicateTemplate(candidateEmbedding, existingEmbeddings)) {
        return { created: false, reason: 'duplicate' }
      }
    }

    const toEvict = pickTemplatesToEvict(existingAutoTemplates, MAX_AUTO_TEMPLATES_PER_ORG)
    if (toEvict.length > 0) {
      await prisma.agentTemplate.deleteMany({ where: { id: { in: toEvict }, organizationId } })
    }

    const configuration = buildAutoTemplateConfig({
      objective,
      integrations,
      model,
      executionId,
      exampleInput: replayable.exampleInput,
      embedding: candidateEmbedding,
    })

    const template = await prisma.agentTemplate.create({
      data: {
        name: title,
        description,
        type: category?.trim() || 'Auto-generated',
        configuration,
        userId,
        organizationId,
      },
      select: { id: true },
    })

    return { created: true, templateId: template.id }
  } catch (error) {
    apiLogger.warn('maybeCreateTemplateFromRun failed', {
      organizationId, agentId, executionId, error: error instanceof Error ? error.message : String(error),
    })
    return { created: false, reason: 'error' }
  }
}
