/**
 * Pure: cross-org leak-prevention filter + mine-before-community sort for
 * GET /api/agent-templates. `rows` must already be serialized (each with
 * `mine` and `autoGenerated` computed for the caller's org — see
 * serializeTemplate in the route). Auto-generated templates encode
 * org-specific process intelligence and must never leak cross-org, so a row
 * is visible only if it isn't auto-generated OR it belongs to the caller
 * (`mine`). Visible rows are then sectioned: the caller's own rows first,
 * then everything else (community + any extra built-ins the caller passes
 * in), preserving each section's incoming relative order.
 *
 * Lives outside route.ts because Next.js route modules may only export
 * route handlers / config — an extra named export there fails the route's
 * generated type check.
 */
export function selectVisibleTemplates<T extends { mine: boolean; autoGenerated: boolean }>(rows: T[], extraCommunity: T[] = []): T[] {
  const visible = rows.filter((t) => !t.autoGenerated || t.mine)
  const mine = visible.filter((t) => t.mine)
  const community = [...extraCommunity, ...visible.filter((t) => !t.mine)]
  return [...mine, ...community]
}
