import { z } from 'zod'
import { prisma, systemPrisma } from '@/lib/prisma'
import { ApiError, withAuthenticatedApi } from '@/lib/server/api-handler'
import { selectVisibleTemplates } from '@/lib/intelligence/template-visibility'
import { SEED_CATALOGUE, serializeSeed } from '@/lib/templates/catalogue'

const templateSchema = z.object({
  name: z.string().min(1),
  description: z.string().default(''),
  category: z.string().default('Custom'),
  instructions: z.string().min(1),
  integrations: z.array(z.string()).default([]),
  skills: z.array(z.string()).default([]),
  tags: z.array(z.string()).default([]),
  model: z.string().default('claude-sonnet-5'),
  exampleOutput: z.string().optional(),
  icon: z.string().trim().max(8).optional(),
  allowSubagents: z.boolean().optional(),
  subagentIds: z.array(z.string()).optional(),
  goal: z.string().max(2000).optional(),
  autoAnswerFromMemory: z.boolean().optional(),
  alwaysStrategize: z.boolean().optional(),
  maxTurns: z.number().int().min(1).max(64).optional(),
  outputFields: z.array(z.object({ name: z.string(), type: z.enum(['string', 'number', 'boolean', 'object', 'array']), description: z.string().optional() })).optional(),
  schedule: z.record(z.string(), z.unknown()).optional(),
  // department-catalogue metadata (additive; community authoring may omit all):
  departments: z.array(z.string()).optional(),
  requiredIntegrations: z.array(z.string()).optional(),
  recommendedIntegrations: z.array(z.string()).optional(),
  kind: z.enum(['agent', 'flow']).optional(),
})

function serializeTemplate(template: any, viewerOrgId?: string) {
  const config = template.configuration && typeof template.configuration === 'object' ? template.configuration as any : {}
  const mine = Boolean(viewerOrgId) && template.organizationId === viewerOrgId
  return {
    id: template.id,
    name: template.name,
    description: template.description || '',
    category: template.type,
    instructions: config.instructions || template.description || '',
    integrations: config.integrations || [],
    skills: config.skills || [],
    tags: config.tags || [],
    model: config.model || 'claude-sonnet-5',
    exampleOutput: config.exampleOutput || '',
    icon: config.icon || '',
    allowSubagents: config.allowSubagents === true,
    subagentIds: Array.isArray(config.subagentIds) ? config.subagentIds : [],
    goal: typeof config.goal === 'string' ? config.goal : '',
    autoAnswerFromMemory: config.autoAnswerFromMemory !== false,
    alwaysStrategize: config.alwaysStrategize === true,
    maxTurns: typeof config.maxTurns === 'number' ? config.maxTurns : 16,
    outputFields: Array.isArray(config.outputFields) ? config.outputFields : [],
    schedule: config.schedule && typeof config.schedule === 'object' ? config.schedule : undefined,
    custom: true,
    authorName: config.authorName || '',
    // Only the creating org may edit/delete a community template.
    mine,
    // Auto-distilled from the org's own successful runs — never a community
    // publish. Surfaced so the UI can badge it ("From your runs") and offer
    // delete, distinct from hand-authored "Community" templates.
    autoGenerated: config.autoGenerated === true,
    // department-catalogue metadata (additive; absent on pre-existing rows):
    departments: Array.isArray(config.departments) ? config.departments : [],
    requiredIntegrations: Array.isArray(config.requiredIntegrations) ? config.requiredIntegrations : [],
    recommendedIntegrations: Array.isArray(config.recommendedIntegrations) ? config.recommendedIntegrations : [],
    kind: config.kind === 'flow' ? 'flow' : 'agent',
    seed: false,
    seedKey: typeof config.seedKey === 'string' ? config.seedKey : '',
  }
}

const builtInTemplates = SEED_CATALOGUE.map(serializeSeed)

export const GET = withAuthenticatedApi(async (request, auth) => {
  // Community templates are a PUBLIC library: readable by every workspace,
  // writable only by the creator's org (PUT/DELETE below stay org-scoped).
  // Auto-generated templates (configuration.autoGenerated === true) are the
  // exception: they encode org-specific process intelligence distilled from
  // that org's own runs and must never leak cross-org, so they're filtered
  // out below unless they belong to the caller's own org.
  // systemPrisma: cross-org read by design — same exemption as /api/skills GET.
  const stored = await systemPrisma.agentTemplate.findMany({
    where: { isActive: true },
    orderBy: { updatedAt: 'desc' },
    take: 500,
  })
  const serialized = stored.map((t) => serializeTemplate(t, auth.organizationId))
  const builtIns = builtInTemplates.map((t) => ({
    ...t,
    custom: false,
    mine: false,
    autoGenerated: false,
    subagentIds: [],
    goal: '',
    autoAnswerFromMemory: true,
    alwaysStrategize: false,
    maxTurns: 16,
    outputFields: [],
    schedule: undefined,
  }))
  // Cross-org leak-prevention + sectioning (caller's own catalogue — auto-
  // generated from their runs plus anything else they authored — before the
  // shared community library): see selectVisibleTemplates.
  const templates = selectVisibleTemplates(serialized, builtIns)
  const limit = Number(request.nextUrl.searchParams.get('limit'))
  return { success: true, templates: limit > 0 ? templates.slice(0, limit) : templates }
})

export const POST = withAuthenticatedApi(async (request, auth) => {
  const data = templateSchema.parse(await request.json())
  const template = await prisma.agentTemplate.create({
    data: {
      name: data.name,
      description: data.description,
      type: data.category,
      configuration: {
        instructions: data.instructions,
        integrations: data.integrations,
        skills: data.skills,
        tags: data.tags,
        model: data.model,
        ...(data.exampleOutput ? { exampleOutput: data.exampleOutput } : {}),
        ...(data.icon ? { icon: data.icon } : {}),
        ...(data.allowSubagents ? { allowSubagents: true } : {}),
        ...(data.subagentIds ? { subagentIds: data.subagentIds } : {}),
        ...(data.goal ? { goal: data.goal } : {}),
        ...(data.autoAnswerFromMemory !== undefined ? { autoAnswerFromMemory: data.autoAnswerFromMemory } : {}),
        ...(data.alwaysStrategize !== undefined ? { alwaysStrategize: data.alwaysStrategize } : {}),
        ...(data.maxTurns !== undefined ? { maxTurns: data.maxTurns } : {}),
        ...(data.outputFields ? { outputFields: data.outputFields } : {}),
        ...(data.schedule ? { schedule: data.schedule } : {}),
        authorName: auth.dbUser.name || auth.dbUser.email || '',
        ...(data.departments ? { departments: data.departments } : {}),
        ...(data.requiredIntegrations ? { requiredIntegrations: data.requiredIntegrations } : {}),
        ...(data.recommendedIntegrations ? { recommendedIntegrations: data.recommendedIntegrations } : {}),
        ...(data.kind ? { kind: data.kind } : {}),
      },
      userId: auth.dbUser.id,
      organizationId: auth.organizationId,
    },
  })
  return { success: true, template: serializeTemplate(template, auth.organizationId) }
})

export const PUT = withAuthenticatedApi(async (request, auth) => {
  const body = z.object({ id: z.string().min(1) }).merge(templateSchema.partial()).parse(await request.json())
  const existing = await prisma.agentTemplate.findFirst({
    where: { id: body.id, organizationId: auth.organizationId },
  })
  if (!existing) throw new ApiError('Template not found', 404, 'NOT_FOUND')
  const config = (existing.configuration && typeof existing.configuration === 'object' ? existing.configuration : {}) as any
  const template = await prisma.agentTemplate.update({
    where: { id: body.id, organizationId: auth.organizationId },
    data: {
      ...(body.name !== undefined && { name: body.name }),
      ...(body.description !== undefined && { description: body.description }),
      ...(body.category !== undefined && { type: body.category }),
      configuration: {
        ...config,
        ...(body.instructions !== undefined && { instructions: body.instructions }),
        ...(body.integrations !== undefined && { integrations: body.integrations }),
        ...(body.skills !== undefined && { skills: body.skills }),
        ...(body.tags !== undefined && { tags: body.tags }),
        ...(body.model !== undefined && { model: body.model }),
        ...(body.exampleOutput !== undefined && { exampleOutput: body.exampleOutput }),
        ...(body.icon !== undefined && { icon: body.icon }),
        ...(body.allowSubagents !== undefined && { allowSubagents: body.allowSubagents }),
        ...(body.subagentIds !== undefined && { subagentIds: body.subagentIds }),
        ...(body.goal !== undefined && { goal: body.goal }),
        ...(body.autoAnswerFromMemory !== undefined && { autoAnswerFromMemory: body.autoAnswerFromMemory }),
        ...(body.alwaysStrategize !== undefined && { alwaysStrategize: body.alwaysStrategize }),
        ...(body.maxTurns !== undefined && { maxTurns: body.maxTurns }),
        ...(body.outputFields !== undefined && { outputFields: body.outputFields }),
        ...(body.schedule !== undefined && { schedule: body.schedule }),
      },
    },
  })
  return { success: true, template: serializeTemplate(template, auth.organizationId) }
})

export const DELETE = withAuthenticatedApi(async (request, auth) => {
  const { id } = z.object({ id: z.string().min(1) }).parse(await request.json())
  const result = await prisma.agentTemplate.deleteMany({
    where: { id, organizationId: auth.organizationId },
  })
  if (!result.count) throw new ApiError('Template not found', 404, 'NOT_FOUND')
  return { success: true }
})
