import { after, before, test } from 'node:test'
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import { NextRequest } from 'next/server'

const TEST_DB = process.env.TEST_DATABASE_URL

if (TEST_DB) {
  process.env.DATABASE_URL = TEST_DB
  process.env.DIRECT_URL = TEST_DB

  let prisma: any
  let seeded: any
  let otherUser: any

  before(async () => {
    ;({ prisma } = await import('@/lib/prisma'))
    const { seedTestOrg, installTestAuth } = await import('@/lib/server/__tests__/test-auth')
    seeded = await seedTestOrg(prisma)
    installTestAuth(seeded.auth)
    otherUser = await prisma.user.create({
      data: {
        supabaseId: crypto.randomUUID(),
        organizationId: seeded.organizationId,
        email: `other-${crypto.randomUUID()}@example.com`,
        isActive: true,
      },
    })

    await Promise.all([
      prisma.agentTask.create({ data: { description: 'mine', objective: 'mine', organizationId: seeded.organizationId, userId: seeded.userId } }),
      prisma.agentTask.create({ data: { description: 'other', objective: 'other', organizationId: seeded.organizationId, userId: otherUser.id, visibility: 'shared' } }),
      prisma.flow.create({ data: { name: 'Mine flow', organizationId: seeded.organizationId, userId: seeded.userId } }),
      prisma.flow.create({ data: { name: 'Other flow', organizationId: seeded.organizationId, userId: otherUser.id, visibility: 'shared' } }),
      prisma.agentExecution.create({ data: { agentType: 'CUSTOM', input: {}, organizationId: seeded.organizationId, userId: seeded.userId } }),
      prisma.agentExecution.create({ data: { agentType: 'CUSTOM', input: {}, organizationId: seeded.organizationId, userId: otherUser.id } }),
      prisma.mcpConnection.create({ data: { organizationId: seeded.organizationId, userId: seeded.userId, name: 'Mine MCP', serverUrl: 'https://mine.example.com/mcp' } }),
      prisma.mcpConnection.create({ data: { organizationId: seeded.organizationId, userId: otherUser.id, name: 'Other MCP', serverUrl: 'https://other.example.com/mcp' } }),
      prisma.mCPAgent.create({ data: { organizationId: seeded.organizationId, userId: seeded.userId, name: 'mine-github', agentType: 'GITHUB', mcpServerUrl: 'https://mine.example.com/klavis', isActive: true } }),
      prisma.mCPAgent.create({ data: { organizationId: seeded.organizationId, userId: otherUser.id, name: 'other-linear', agentType: 'LINEAR', mcpServerUrl: 'https://other.example.com/klavis', isActive: true } }),
      prisma.agentTemplate.create({ data: { name: 'Shared hand template', type: 'Custom', description: 'safe to share', organizationId: seeded.organizationId, userId: otherUser.id } }),
      prisma.agentTemplate.create({ data: { name: 'Other run-derived template', type: 'Custom', description: 'private process', configuration: { autoGenerated: true }, organizationId: seeded.organizationId, userId: otherUser.id } }),
    ])
  })

  after(async () => {
    if (seeded) await seeded.cleanup()
  })

  const request = (path: string) => new NextRequest(new URL(`http://test${path}`))
  const json = async (response: Response) => response.json() as Promise<any>

  test('agents, flows, executions, and custom MCP rows are owner-only', async () => {
    const agents = await json((await import('../agents/route')).GET(request('/api/agents')))
    assert.deepEqual(agents.agents.map((row: any) => row.title), ['mine'])

    const flows = await json((await import('../flows/route')).GET(request('/api/flows')))
    assert.deepEqual(flows.flows.map((row: any) => row.name), ['Mine flow'])

    const executions = await json((await import('../agents/activity/route')).GET(request('/api/agents/activity')))
    assert.equal(executions.activities.length, 1)
    assert.equal(executions.activities[0].userId, seeded.userId)

    const mcp = await json((await import('../mcp-connections/route')).GET(request('/api/mcp-connections')))
    assert.deepEqual(mcp.connections.map((row: any) => row.name), ['Mine MCP'])
  })

  test('connecting a custom integration ignores supplied ownership and saves it for the authenticated user', async () => {
    const response = await (await import('../mcp-connections/route')).POST(new NextRequest('http://test/api/mcp-connections', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name: 'New personal MCP',
        serverUrl: 'https://1.1.1.1/mcp',
        authType: 'none',
        isActive: false,
        // A malicious/buggy client cannot assign the connection to somebody
        // else or another organization; the route derives both from auth.
        userId: otherUser.id,
        organizationId: crypto.randomUUID(),
      }),
    }))
    assert.equal(response.status, 200)
    const row = await prisma.mcpConnection.findFirst({
      where: { name: 'New personal MCP', organizationId: seeded.organizationId },
    })
    assert.equal(row?.userId, seeded.userId)
    assert.equal(row?.organizationId, seeded.organizationId)
  })

  test('integration availability uses only the acting user credentials', async () => {
    const available = await json((await import('../integrations/available/route')).GET(request('/api/integrations/available')))
    assert.deepEqual(available.connections.map((row: any) => row.name), ['Mine MCP'])
    const connected = available.tools.filter((row: any) => row.connected).map((row: any) => row.key.toLowerCase())
    assert.ok(connected.includes('github'))
    assert.ok(!connected.includes('linear'))
  })

  test('hand-authored templates are shared but another user run-derived template is hidden', async () => {
    const body = await json((await import('../agent-templates/route')).GET(request('/api/agent-templates')))
    const names = body.templates.map((row: any) => row.name)
    assert.ok(names.includes('Shared hand template'))
    assert.ok(!names.includes('Other run-derived template'))
  })
}
