import { test } from 'node:test'
import assert from 'node:assert/strict'
import { selectVisibleTemplates } from '../template-visibility'

/**
 * Hand-built serialized rows, shaped as serializeTemplate() produces them for
 * caller org "org-a": `mine` and `visibleToViewer` already resolved.
 *
 * `visibleToViewer` used to be derived here from `autoGenerated`. It is now
 * decided once, upstream, by templateVisibleTo — because that rule also has to
 * cover the explicit org/community setting a template saved from a flow
 * carries, and two places encoding who may read a template is a data leak
 * waiting to happen rather than a duplication smell.
 *
 * So these tests own ORDERING. The rule itself is covered in
 * lib/templates/__tests__/visibility.test.ts.
 */
type Row = { id: string; mine: boolean; visibleToViewer: boolean }

test('a row the caller may not see is dropped, whatever the reason upstream decided', () => {
  const rows: Row[] = [
    { id: 'a-auto', mine: true, visibleToViewer: true }, // caller's own auto-generated
    { id: 'b-auto', mine: false, visibleToViewer: false }, // another org's — upstream said no
    { id: 'community', mine: false, visibleToViewer: true },
    { id: 'a-hand', mine: true, visibleToViewer: true },
  ]

  const ids = selectVisibleTemplates(rows).map((t) => t.id)

  assert.ok(!ids.includes('b-auto'), 'a row marked not-visible must never be returned')
  assert.deepEqual(new Set(ids), new Set(['a-auto', 'community', 'a-hand']))

  // The caller's own rows (in whatever relative order they arrived) come
  // before the community section.
  assert.ok(ids.indexOf('a-auto') < ids.indexOf('community'), 'mine rows must sort before community')
  assert.ok(ids.indexOf('a-hand') < ids.indexOf('community'), 'mine rows must sort before community')
})

test('extra community rows (e.g. built-ins) land after mine, ahead of fetched community', () => {
  const rows: Row[] = [{ id: 'a-auto', mine: true, visibleToViewer: true }]
  const extra: Row[] = [{ id: 'builtin', mine: false, visibleToViewer: true }]
  assert.deepEqual(selectVisibleTemplates(rows, extra).map((t) => t.id), ['a-auto', 'builtin'])
})

test('an all-visible set is only re-sectioned, never filtered', () => {
  const rows: Row[] = [
    { id: 'community-1', mine: false, visibleToViewer: true },
    { id: 'a-hand', mine: true, visibleToViewer: true },
  ]
  assert.deepEqual(selectVisibleTemplates(rows).map((t) => t.id), ['a-hand', 'community-1'])
})

test('seed builtIns lead the community section, after mine', () => {
  const rows: Row[] = [
    { id: 'mine', mine: true, visibleToViewer: true },
    { id: 'community', mine: false, visibleToViewer: true },
  ]
  const seeds: Row[] = [{ id: 'seed:x', mine: false, visibleToViewer: true }]
  assert.deepEqual(selectVisibleTemplates(rows, seeds).map((t) => t.id), ['mine', 'seed:x', 'community'])
})

// A caller's OWN row is still dropped if upstream marked it invisible. The
// filter must not second-guess the rule by re-adding `|| mine`.
test('mine does not override an upstream not-visible decision', () => {
  const rows: Row[] = [{ id: 'mine-hidden', mine: true, visibleToViewer: false }]
  assert.deepEqual(selectVisibleTemplates(rows), [])
})
