import { test } from 'node:test'
import assert from 'node:assert/strict'
import { selectVisibleTemplates } from '../template-visibility'

// Hand-built serialized rows, shaped as serializeTemplate() would produce
// them for caller org "org-a": `mine` and `autoGenerated` already resolved.
type Row = { id: string; mine: boolean; autoGenerated: boolean }

test('selectVisibleTemplates: excludes another org\'s auto-generated template, keeps everything else, sorts mine first', () => {
  const rows: Row[] = [
    { id: 'a-auto', mine: true, autoGenerated: true }, // caller org A's own auto-generated
    { id: 'b-auto', mine: false, autoGenerated: true }, // org B's auto-generated — must be excluded
    { id: 'community', mine: false, autoGenerated: false }, // hand-authored community template
    { id: 'a-hand', mine: true, autoGenerated: false }, // caller org A's own hand-authored template
  ]

  const result = selectVisibleTemplates(rows)
  const ids = result.map((t) => t.id)

  assert.ok(!ids.includes('b-auto'), 'another org\'s auto-generated template must never be visible')
  assert.deepEqual(new Set(ids), new Set(['a-auto', 'community', 'a-hand']))

  // Caller's own rows (in whatever relative order they arrived) come before
  // the community section.
  const aAutoIdx = ids.indexOf('a-auto')
  const aHandIdx = ids.indexOf('a-hand')
  const communityIdx = ids.indexOf('community')
  assert.ok(aAutoIdx < communityIdx, 'mine rows must sort before community')
  assert.ok(aHandIdx < communityIdx, 'mine rows must sort before community')
})

test('selectVisibleTemplates: includes extra community rows (e.g. built-ins) after mine, before/with fetched community', () => {
  const rows: Row[] = [{ id: 'a-auto', mine: true, autoGenerated: true }]
  const extra: Row[] = [{ id: 'builtin', mine: false, autoGenerated: false }]
  const result = selectVisibleTemplates(rows, extra)
  assert.deepEqual(
    result.map((t) => t.id),
    ['a-auto', 'builtin'],
  )
})

test('selectVisibleTemplates: no auto-generated rows at all is unaffected', () => {
  const rows: Row[] = [
    { id: 'community-1', mine: false, autoGenerated: false },
    { id: 'a-hand', mine: true, autoGenerated: false },
  ]
  const result = selectVisibleTemplates(rows)
  assert.deepEqual(
    result.map((t) => t.id),
    ['a-hand', 'community-1'],
  )
})
