/**
 * Who may read a stored template.
 *
 * AgentTemplate is a PUBLIC cross-org library today: both GET
 * /api/agent-templates and loadDbTemplateRecipe read via systemPrisma with no
 * organization filter, and the only private rows are the ones carrying
 * `autoGenerated: true`. Saving a flow as a template therefore cannot just
 * write a row — that would publish the flow's graph, prompts, step structure
 * and connection names to every workspace on the platform.
 *
 * These rules add an explicit `visibility`, and the backward-compatibility
 * case is the one that matters most: an ABSENT value must keep meaning
 * "public", or the existing community library silently disappears the day
 * this ships.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { templateVisibleTo } from '../visibility'

const OWNER = 'org-owner'
const OTHER = 'org-other'

test('a template with no visibility stays public — existing rows must not vanish', () => {
  assert.equal(templateVisibleTo({}, OWNER, OTHER), true)
})

test('an explicitly community template is readable cross-org', () => {
  assert.equal(templateVisibleTo({ visibility: 'community' }, OWNER, OTHER), true)
})

// The new default for anything saved from a flow.
test('an org template is hidden from other workspaces', () => {
  assert.equal(templateVisibleTo({ visibility: 'org' }, OWNER, OTHER), false)
})

test('an org template is readable by its own workspace', () => {
  assert.equal(templateVisibleTo({ visibility: 'org' }, OWNER, OWNER), true)
})

// The existing private-template mechanism must keep working unchanged —
// auto-generated templates encode one org's process intelligence.
test('an auto-generated template stays org-private even with no visibility set', () => {
  assert.equal(templateVisibleTo({ autoGenerated: true }, OWNER, OTHER), false)
  assert.equal(templateVisibleTo({ autoGenerated: true }, OWNER, OWNER), true)
})

// Defence in depth: if the two flags ever disagree, the private one wins.
test('autoGenerated and community together resolve to private, not public', () => {
  assert.equal(templateVisibleTo({ autoGenerated: true, visibility: 'community' }, OWNER, OTHER), false)
})

// An unrecognised value must not be treated as a publish.
test('an unknown visibility value is treated as org-private, not public', () => {
  assert.equal(templateVisibleTo({ visibility: 'everyone' }, OWNER, OTHER), false)
})

// A viewer with no organization (an unauthenticated or system read path) must
// never receive private rows by accident.
test('a null viewer org sees only public templates', () => {
  assert.equal(templateVisibleTo({}, OWNER, null), true)
  assert.equal(templateVisibleTo({ visibility: 'org' }, OWNER, null), false)
})

// The config comes out of a Json column, so it can be anything.
test('a malformed configuration is treated as public, matching an absent one', () => {
  assert.equal(templateVisibleTo(null, OWNER, OTHER), true)
  assert.equal(templateVisibleTo('nonsense' as unknown as Record<string, unknown>, OWNER, OTHER), true)
})
