/**
 * Who may read a stored template.
 *
 * `AgentTemplate` is a public cross-org library by default — `GET
 * /api/agent-templates` and `loadDbTemplateRecipe` both read via
 * `systemPrisma` with no organization filter, because the community catalogue
 * is meant to be shared. The only private rows are those carrying
 * `autoGenerated: true`, which encode one workspace's own process
 * intelligence.
 *
 * That default is fine for hand-authored catalogue entries and wrong for
 * anything saved out of a user's own flow: a saved flow template carries its
 * graph, its prompts, its step structure and its connection names. So
 * save-as-template writes an explicit `visibility: 'org'`, and this function
 * is the single place both read paths agree on what that means.
 *
 * ONE definition on purpose — the same reason `nodeVisibleTo` is shared
 * between the two graph stores. Two copies of a visibility rule drift, and a
 * drifted visibility rule is a data leak rather than a bug.
 */

/** Stored on `AgentTemplate.configuration`. Absent is a meaningful state. */
export type TemplateVisibility = 'org' | 'community'

/**
 * Is `config`'s template readable by `viewerOrgId`?
 *
 * `ownerOrgId` is the row's own organization. `viewerOrgId` may be null for a
 * system or unauthenticated read path, which must never be handed a private
 * row by accident.
 *
 * The resolution order matters:
 *
 *  1. `autoGenerated` wins over everything. It is the pre-existing privacy
 *     mechanism, and if the two flags ever disagree the private answer is the
 *     safe one.
 *  2. An ABSENT `visibility` means public. This is deliberate backward
 *     compatibility: every row written before this field existed is public
 *     today, and defaulting them to private would silently empty the
 *     community catalogue the day this ships.
 *  3. `'community'` is public; `'org'` — and anything unrecognised — is
 *     private. An unknown value must never resolve to a publish.
 */
export function templateVisibleTo(
  config: Record<string, unknown> | null | undefined,
  ownerOrgId: string,
  viewerOrgId: string | null,
): boolean {
  const own = viewerOrgId != null && viewerOrgId === ownerOrgId
  // A Json column can hold anything; a non-object is treated as "no config",
  // which is the backward-compatible public case.
  const settings = config && typeof config === 'object' && !Array.isArray(config) ? config : {}

  if (settings.autoGenerated === true) return own

  const visibility = settings.visibility
  if (visibility === undefined || visibility === null) return true
  if (visibility === 'community') return true
  return own
}

/**
 * The visibility a template saved from a flow is written with.
 *
 * Publishing to the shared library is a separate, deliberate act — never a
 * side effect of keeping your own work.
 */
export const SAVED_FLOW_TEMPLATE_VISIBILITY: TemplateVisibility = 'org'
