/**
 * The one-or-two-word role shown under an agent's name on the roster.
 *
 * People name agents anything ("Monday thing v2"), so the roster shows what an
 * agent DOES rather than trusting its title. That description is generated by a
 * model from user-authored instructions, which makes this module the trust
 * boundary: nothing reaches a rendered label without passing these rules.
 *
 * Pure so the generation route, the PATCH validator, and the client all agree
 * on what a legal label is.
 */
import type { Department } from '@/lib/templates/departments'

export const ROLE_LABEL_MAX_CHARS = 24
export const ROLE_LABEL_MAX_WORDS = 2

/** Honest department roles. Never invents a job title the user didn't ask for. */
const DEPARTMENT_FALLBACKS: Record<Department, string> = {
  sales: 'Sales',
  engineering: 'Engineering',
  marketing: 'Marketing',
  finance: 'Finance',
  csm: 'Customer Success',
  general: 'Generalist',
}

/**
 * What to show before generation has run (or when no model provider is
 * configured). `specialistArea` is always set by serializeAgent, so a tile is
 * never label-less.
 */
export function fallbackRoleLabel(specialistArea?: string | null): string {
  const key = specialistArea?.trim().toLowerCase()
  return (key && DEPARTMENT_FALLBACKS[key as Department]) || DEPARTMENT_FALLBACKS.general
}

/**
 * A word carrying any uppercase is intentional — 'QA', 'GTM', 'McKinsey'.
 * Blindly capitalizing the first letter alone would render those as 'Qa' and
 * 'Gtm', and acronyms are exactly the labels people notice.
 */
function titleCaseWord(word: string): string {
  if (/[A-Z]/.test(word)) return word
  return word.charAt(0).toUpperCase() + word.slice(1)
}

/**
 * Coerce raw model output into a legal label, or null if it can't be salvaged.
 *
 * Rejecting beats clipping: a label truncated mid-word reads as a rendering
 * bug, whereas null falls back to the department, which always reads correctly.
 */
export function normalizeRoleLabel(raw: unknown): string | null {
  if (typeof raw !== 'string') return null
  const cleaned = raw
    // Models like to wrap short answers in markdown.
    .replace(/[*_`#]/g, '')
    // Everything outside this set — emoji, markup, brackets, quotes — becomes a
    // space. Markup then splits into extra words and fails the word-count rule
    // below, so an injected payload can never land in a label.
    .replace(/[^A-Za-z0-9&/'’.\- ]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^[.\-/&,:;'’]+|[.\-/&,:;'’]+$/g, '')
    .trim()
  if (!cleaned || cleaned.length > ROLE_LABEL_MAX_CHARS) return null
  const words = cleaned.split(' ')
  if (words.length > ROLE_LABEL_MAX_WORDS) return null
  return words.map(titleCaseWord).join(' ')
}
